# Generated by Django 4.2.6 on 2023-12-21 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_product_id', models.CharField(max_length=100)),
                ('account_code', models.CharField(max_length=100)),
                ('crawl_page_counter', models.CharField(max_length=100)),
                ('postal_zip_code', models.CharField(max_length=100)),
                ('postal_zip_name', models.CharField(max_length=100)),
                ('store_code', models.CharField(max_length=100)),
                ('place_name', models.CharField(max_length=100)),
                ('admin_name1', models.CharField(max_length=100)),
                ('bundle_versions_row_pk_hash', models.CharField(max_length=100)),
                ('major_version_end_time', models.CharField(max_length=100)),
                ('bundle_variant_field_mapping', models.CharField(max_length=100)),
                ('bundle_definition', models.CharField(max_length=100)),
                ('fulfilment_modes', models.CharField(max_length=100)),
                ('seller_name', models.CharField(max_length=100)),
                ('bundle_match_type', models.CharField(max_length=100)),
                ('bundle_definition_hash', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=100)),
                ('reference_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app1.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('reference_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app1.product')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_price', models.CharField(max_length=100)),
                ('reference_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app1.product')),
            ],
        ),
    ]
